# Generated by tools/bake_enemy_projectiles.gd; regenerate rather than edit.
extends RefCounted

const ATLAS: Texture2D = preload("res://assets/vfx/enemy_projectiles.png")
const REGIONS := {
	"body:f252a1ff:9.0": Rect2(2, 2, 80, 80),
	"body:87e021ff:9.0": Rect2(86, 2, 80, 80),
	"body:ff6e40ff:9.0": Rect2(170, 2, 80, 80),
	"body:ff8538ff:9.0": Rect2(254, 2, 80, 80),
	"body:59eb4fff:9.0": Rect2(338, 2, 80, 80),
	"body:f5406eff:9.0": Rect2(422, 2, 80, 80),
	"body:ff6e40ff:21.7": Rect2(506, 2, 96, 96),
	"halo:ff6e40ff:31.0": Rect2(606, 2, 136, 136),
	"body:59eb4fff:21.7": Rect2(746, 2, 96, 96),
	"halo:59eb4fff:31.0": Rect2(846, 2, 136, 136),
	"body:f5406eff:21.7": Rect2(2, 142, 96, 96),
	"halo:f5406eff:31.0": Rect2(102, 142, 136, 136),
	"body:ff6e40ff:23.8": Rect2(242, 142, 104, 104),
	"halo:ff6e40ff:34.0": Rect2(350, 142, 148, 148),
	"body:59eb4fff:23.8": Rect2(502, 142, 104, 104),
	"halo:59eb4fff:34.0": Rect2(610, 142, 148, 148),
	"body:f5406eff:23.8": Rect2(762, 142, 104, 104),
	"halo:f5406eff:34.0": Rect2(870, 142, 148, 148),
	"body:ff6e40ff:29.4": Rect2(2, 294, 128, 128),
	"halo:ff6e40ff:42.0": Rect2(134, 294, 180, 180),
	"body:59eb4fff:29.4": Rect2(318, 294, 128, 128),
	"halo:59eb4fff:42.0": Rect2(450, 294, 180, 180),
	"body:f5406eff:29.4": Rect2(634, 294, 128, 128),
	"halo:f5406eff:42.0": Rect2(766, 294, 180, 180),
	"body:ff6e40ff:35.0": Rect2(2, 478, 148, 148),
	"halo:ff6e40ff:50.0": Rect2(154, 478, 212, 212),
	"body:59eb4fff:35.0": Rect2(370, 478, 148, 148),
	"halo:59eb4fff:50.0": Rect2(522, 478, 212, 212),
	"body:f5406eff:35.0": Rect2(738, 478, 148, 148),
	"halo:f5406eff:50.0": Rect2(2, 694, 212, 212),
}

static var textures: Dictionary[String, Texture2D] = {}

static func find(key: String) -> Texture2D:
	if not REGIONS.has(key):
		return null
	if not textures.has(key):
		var region := AtlasTexture.new()
		region.atlas = ATLAS
		region.region = REGIONS[key]
		textures[key] = region
	return textures[key]
