# Generated by tools/bake_enemy_sprites.gd; preserve source artwork.
extends RefCounted

const ATLAS: Texture2D = preload("res://assets/enemies/combat_atlas.png")
const REGIONS := {
	"res://assets/enemies/plaque.png": Rect2(4, 4, 1254, 1254),
	"res://assets/enemies/bacteria.png": Rect2(1262, 4, 1254, 1254),
	"res://assets/enemies/sugar.png": Rect2(4, 1262, 1254, 1254),
	"res://assets/enemies/acid_spitter.png": Rect2(1262, 1262, 1230, 1278),
	"res://assets/enemies/poison_germ.png": Rect2(4, 2544, 768, 1024),
	"res://assets/enemies/gum_biter.png": Rect2(776, 2544, 768, 1024),
}
