# Generated by tools/bake_combat_textures.gd; regenerate rather than edit.
extends RefCounted

const ATLAS: Texture2D = preload("res://assets/vfx/combat_textures.png")
const REGIONS := {
	"enemy_shadow": Rect2(2, 2, 64, 64),
	"loot:xp": Rect2(70, 2, 64, 64),
	"loot:coin": Rect2(138, 2, 64, 64),
	"loot:chest": Rect2(206, 2, 64, 64),
	"tail:c2f5ffff:7.0": Rect2(274, 2, 128, 128),
	"outline:c2f5ffff:7.0": Rect2(406, 2, 128, 128),
	"body:c2f5ffff:7.0": Rect2(538, 2, 128, 128),
	"tail:3dccffff:7.0": Rect2(670, 2, 128, 128),
	"outline:3dccffff:7.0": Rect2(802, 2, 128, 128),
	"body:3dccffff:7.0": Rect2(2, 134, 128, 128),
	"tail:ffc245ff:11.0": Rect2(134, 134, 128, 128),
	"outline:ffc245ff:11.0": Rect2(266, 134, 128, 128),
	"body:ffc245ff:11.0": Rect2(398, 134, 128, 128),
	"tail:45e6abff:11.0": Rect2(530, 134, 128, 128),
	"outline:45e6abff:11.0": Rect2(662, 134, 128, 128),
	"body:45e6abff:11.0": Rect2(794, 134, 128, 128),
	"tail:b0b8ccff:11.0": Rect2(2, 266, 128, 128),
	"outline:b0b8ccff:11.0": Rect2(134, 266, 128, 128),
	"body:b0b8ccff:11.0": Rect2(266, 266, 128, 128),
	"rocket:b0ffc7ff": Rect2(398, 266, 160, 160),
	"tail:40e6ffff:7.0": Rect2(562, 266, 128, 128),
	"outline:40e6ffff:7.0": Rect2(694, 266, 128, 128),
	"body:40e6ffff:7.0": Rect2(826, 266, 128, 128),
	"tail:ffdb66ff:7.0": Rect2(2, 430, 128, 128),
	"outline:ffdb66ff:7.0": Rect2(134, 430, 128, 128),
	"body:ffdb66ff:7.0": Rect2(266, 430, 128, 128),
	"tail:a6ffe0ff:7.0": Rect2(398, 430, 128, 128),
	"outline:a6ffe0ff:7.0": Rect2(530, 430, 128, 128),
	"body:a6ffe0ff:7.0": Rect2(662, 430, 128, 128),
}

static var textures: Dictionary[String, Texture2D] = {}

static func find(key: String) -> Texture2D:
	if not REGIONS.has(key):
		return null
	if not textures.has(key):
		var region := AtlasTexture.new()
		region.atlas = ATLAS
		region.region = REGIONS[key]
		textures[key] = region
	return textures[key]
