extends SceneTree

# Pack full-resolution source artwork without resizing, cropping or repainting.
# Two sprites per row keep wasted atlas area small. Four transparent pixels
# between cells prevent linear filtering from bleeding into adjacent artwork.
const SOURCES := ["plaque", "bacteria", "sugar", "acid_spitter", "poison_germ", "gum_biter"]
const GAP := 4

func _initialize() -> void:
	var images: Array[Image] = []
	var regions: Array[Rect2i] = []
	var extent := Vector2i.ZERO
	var row_y := GAP
	for row in 3:
		var x := GAP
		var row_height := 0
		for column in 2:
			var name: String = SOURCES[row * 2 + column]
			var image: Image = load("res://assets/enemies/%s.png" % name).get_image()
			image.convert(Image.FORMAT_RGBA8)
			images.append(image)
			regions.append(Rect2i(Vector2i(x, row_y), image.get_size()))
			x += image.get_width() + GAP
			row_height = maxi(row_height, image.get_height())
		row_y += row_height + GAP
		extent.x = maxi(extent.x, x)
	extent.y = row_y
	var atlas := Image.create(extent.x, extent.y, false, Image.FORMAT_RGBA8)
	DirAccess.make_dir_recursive_absolute("res://assets/enemies/packed")
	var manifest := "# Generated by tools/bake_enemy_sprites.gd; preserve source artwork.\nextends RefCounted\n\nconst ATLAS: Texture2D = preload(\"res://assets/enemies/combat_atlas.png\")\nconst REGIONS := {\n"
	for index in SOURCES.size():
		var region := regions[index]
		atlas.blit_rect(images[index], Rect2i(Vector2i.ZERO, images[index].get_size()), region.position)
		manifest += "\t\"res://assets/enemies/%s.png\": Rect2(%d, %d, %d, %d),\n" % [SOURCES[index], region.position.x, region.position.y, region.size.x, region.size.y]
		var cell := FileAccess.open("res://assets/enemies/packed/%s.tres" % SOURCES[index], FileAccess.WRITE)
		cell.store_string("[gd_resource type=\"AtlasTexture\" load_steps=2 format=3]\n\n[ext_resource type=\"Texture2D\" path=\"res://assets/enemies/combat_atlas.png\" id=\"1\"]\n\n[resource]\natlas = ExtResource(\"1\")\nregion = Rect2(%d, %d, %d, %d)\nfilter_clip = true\n" % [region.position.x, region.position.y, region.size.x, region.size.y])
	manifest += "}\n"
	var result := atlas.save_png("res://assets/enemies/combat_atlas.png")
	if result != OK:
		push_error("Could not write enemy atlas: %s" % result)
		quit(1)
		return
	var file := FileAccess.open("res://scripts/enemies/prepared_enemy_sprites.gd", FileAccess.WRITE)
	file.store_string(manifest)
	print("Packed %d full-resolution enemy sprites into %s" % [SOURCES.size(), extent])
	quit()
