extends SceneTree

const ATLAS_WIDTH := 1024
const PADDING := 2

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var entries: Array[Dictionary] = []
	var cursor := Vector2i(PADDING, PADDING)
	var row_height := 0
	for spec in EnemyProjectileVisuals.standard_specs():
		var image := EnemyProjectileVisuals.body_image(spec.tint, spec.radius) if spec.kind == "body" else EnemyProjectileVisuals.halo_image(spec.tint, spec.radius)
		if cursor.x + image.get_width() + PADDING > ATLAS_WIDTH:
			cursor.x = PADDING
			cursor.y += row_height + PADDING * 2
			row_height = 0
		entries.append({"key": "%s:%s:%s" % [spec.kind, spec.tint.to_html(), spec.radius], "image": image, "at": cursor})
		cursor.x += image.get_width() + PADDING * 2
		row_height = maxi(row_height, image.get_height())
	var atlas := Image.create(ATLAS_WIDTH, cursor.y + row_height + PADDING, false, Image.FORMAT_RGBA8)
	var source := "# Generated by tools/bake_enemy_projectiles.gd; regenerate rather than edit.\nextends RefCounted\n\nconst ATLAS: Texture2D = preload(\"res://assets/vfx/enemy_projectiles.png\")\nconst REGIONS := {\n"
	for entry in entries:
		var image: Image = entry.image
		atlas.blit_rect(image, Rect2i(Vector2i.ZERO, image.get_size()), entry.at)
		source += "\t\"%s\": Rect2(%d, %d, %d, %d),\n" % [entry.key, entry.at.x, entry.at.y, image.get_width(), image.get_height()]
	source += "}\n\nstatic var textures: Dictionary[String, Texture2D] = {}\n\nstatic func find(key: String) -> Texture2D:\n\tif not REGIONS.has(key):\n\t\treturn null\n\tif not textures.has(key):\n\t\tvar region := AtlasTexture.new()\n\t\tregion.atlas = ATLAS\n\t\tregion.region = REGIONS[key]\n\t\ttextures[key] = region\n\treturn textures[key]\n"
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path("res://assets/vfx"))
	var error := atlas.save_png("res://assets/vfx/enemy_projectiles.png")
	if error != OK:
		push_error("Could not save projectile atlas")
		quit(1)
		return
	var file := FileAccess.open("res://scripts/enemies/prepared_projectile_textures.gd", FileAccess.WRITE)
	if file == null:
		push_error("Could not save projectile atlas regions")
		quit(1)
		return
	file.store_string(source)
	print("Baked %d projectile images: %s" % [entries.size(), atlas.get_size()])
	quit()
