extends SceneTree

const WIDTH := 2048
const RADII := [20, 24, 26, 31]

class Glyphs extends Node2D:
	var entries: Array[Dictionary] = []
	func _draw() -> void:
		for entry in entries:
			var at: Vector2 = entry.rect.get_center()
			if entry.kind == "arc" and entry.step > 0:
				draw_arc(at, entry.radius * 2, -PI / 2, -PI / 2 + TAU * entry.step / 64.0, 32, Color.WHITE, 8.0)
			elif entry.kind == "circle":
				draw_circle(at, 64, Color.WHITE)
			elif entry.kind == "line":
				draw_rect(entry.rect, Color.WHITE)

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	if DisplayServer.get_name() == "headless":
		push_error("Bake combat glyphs with rendering enabled")
		quit(1)
		return
	var viewport := SubViewport.new()
	var glyphs := Glyphs.new()
	for radius in RADII:
		for step in 65:
			glyphs.entries.append({"key": "%s:%s" % [radius, step], "kind": "arc", "radius": radius, "step": step, "size": Vector2i.ONE * (radius + 4) * 4})
	glyphs.entries.append({"key": "circle", "kind": "circle", "size": Vector2i(152, 152)})
	glyphs.entries.append({"key": "line", "kind": "line", "size": Vector2i(4, 4)})
	var cursor := Vector2i(2, 2)
	var row_height := 0
	var source := "# Generated by tools/bake_combat_glyphs.gd.\nextends RefCounted\n\nconst REGIONS := {\n"
	for entry in glyphs.entries:
		if cursor.x + entry.size.x + 2 > WIDTH:
			cursor.x = 2
			cursor.y += row_height + 4
			row_height = 0
		entry.rect = Rect2(cursor, entry.size)
		source += "\t\"%s\": Rect2(%s, %s, %s, %s),\n" % [entry.key, cursor.x, cursor.y, entry.size.x, entry.size.y]
		cursor.x += entry.size.x + 4
		row_height = maxi(row_height, entry.size.y)
	source += "}\n"
	viewport.size = Vector2i(WIDTH, cursor.y + row_height + 2)
	viewport.transparent_bg = true
	viewport.world_2d = World2D.new()
	viewport.render_target_update_mode = SubViewport.UPDATE_ONCE
	root.add_child(viewport)
	viewport.add_child(glyphs)
	await RenderingServer.frame_post_draw
	var image := viewport.get_texture().get_image()
	var error := image.save_png("res://assets/vfx/combat_glyphs.png")
	if error != OK:
		push_error("Cannot save combat glyph atlas")
		quit(1)
		return
	var file := FileAccess.open("res://scripts/systems/prepared_combat_glyphs.gd", FileAccess.WRITE)
	if file == null:
		push_error("Cannot save combat glyph regions")
		quit(1)
		return
	file.store_string(source)
	viewport.free()
	print("Baked %s warning arcs, circle and line glyphs: %s" % [RADII.size() * 65, image.get_size()])
	quit()
